/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginRegister;

import java.awt.Color;
import java.nio.charset.Charset;
import java.util.Random;
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import ConnectionDB.KoneksiDB;
import PembeliDashBoard.MainMenu;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author Ridho Gymnastiar Al Rasyid
 */
public class LoginAndRegisterForm extends javax.swing.JFrame {

    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(204, 204, 204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    Border textField_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);

    private KoneksiDB db = new KoneksiDB();
    private boolean flag1, flag2, flag3, flag4, flag5;
    public static User user;
    public static Membership member;

    /**
     * Creates new form RIDHO!!!!!!!
     */
    public LoginAndRegisterForm() {
        initComponents();
        this.setBackground(new Color(0, 0, 0, 0));
        panel_container.setBackground(new Color(0, 0, 0, 0));
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/logoapk.png"));
        this.setIconImage(icon.getImage());
        
        this.setLocationRelativeTo(null);
        panel_login.setVisible(true);
        panel_register.setVisible(false);
        panel_lupaPass.setVisible(false);
        panel_ChangePass.setVisible(false);

        // design jLabel Login
        jl_Login.setBorder(red_top_border);
        jl_Login.setBackground(Color.white);
        jl_Login.setForeground(Color.black);

        // design jLabel register 
        jl_Register.setBorder(default_top_border);
        jl_Register.setBackground(new Color(115, 3, 252));
        jl_Register.setForeground(Color.white);

        jTextField_Login_username.setBorder(textField_border);
        jPasswordField_Login_pass.setBorder(textField_border);
        jTextField_Register_fullname.setBorder(textField_border);
        jTextField_Register_username.setBorder(textField_border);
        jTextField_Register_email.setBorder(textField_border);
        jPasswordField_Register_pass.setBorder(textField_border);
        jTextField_Register_phone.setBorder(textField_border);
        jTextField_emailforgot.setBorder(textField_border);
        jPasswordField_pwbaru.setBorder(textField_border);
        jPasswordField_pwbaruconfirm.setBorder(textField_border);
    }

    public JPanel getPanelMain() {
        return panel_main;
    }

    public JPanel getPanelForgot() {
        return panel_lupaPass;
    }

    public JPanel getPanelCP() {
        return panel_ChangePass;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_container = new javax.swing.JPanel();
        panel_main = new javax.swing.JPanel();
        jl_Login = new javax.swing.JLabel();
        jl_Register = new javax.swing.JLabel();
        panel_login = new javax.swing.JPanel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jTextField_Login_username = new javax.swing.JTextField();
        jPasswordField_Login_pass = new javax.swing.JPasswordField();
        jButton_Login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgotPw = new javax.swing.JLabel();
        panel_register = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Register_phone = new javax.swing.JTextField();
        jTextField_Register_fullname = new javax.swing.JTextField();
        jTextField_Register_email = new javax.swing.JTextField();
        jButton_GeneratePass = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPasswordField_Register_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_Register_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton_Register = new javax.swing.JButton();
        panel_lupaPass = new javax.swing.JPanel();
        jPasswordField_pwbaru = new javax.swing.JPasswordField();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPasswordField_pwbaruconfirm = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jTextField_emailforgot = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jl_forgot = new javax.swing.JLabel();
        error_pass = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        panel_ChangePass = new javax.swing.JPanel();
        jPasswordField_pwlama_cp = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        jPasswordField_pwbaru_cp = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPasswordField_pwbaruconfirm_cp = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jl_cpass = new javax.swing.JLabel();
        error_pass1 = new javax.swing.JLabel();
        btn_cpass = new javax.swing.JButton();
        jButton_Reset = new javax.swing.JButton();
        exit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_main.setBackground(new java.awt.Color(255, 255, 255));
        panel_main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_Login.setBackground(new java.awt.Color(115, 3, 252));
        jl_Login.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jl_Login.setForeground(new java.awt.Color(255, 255, 255));
        jl_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Login.setText("Login");
        jl_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_Login.setOpaque(true);
        jl_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_LoginMouseClicked(evt);
            }
        });
        panel_main.add(jl_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 135, 40));

        jl_Register.setBackground(new java.awt.Color(115, 3, 252));
        jl_Register.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jl_Register.setForeground(new java.awt.Color(255, 255, 255));
        jl_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_Register.setText("Register");
        jl_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jl_Register.setOpaque(true);
        jl_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_RegisterMouseClicked(evt);
            }
        });
        panel_main.add(jl_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 135, 40));

        panel_login.setBackground(new java.awt.Color(255, 255, 255));
        panel_login.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(115, 3, 252)));
        panel_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCheckBox2.setText("Show Password");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });
        panel_login.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 250, 20));

        jTextField_Login_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Login_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Login_username.setText("username");
        jTextField_Login_username.setOpaque(false);
        jTextField_Login_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Login_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Login_usernameFocusLost(evt);
            }
        });
        panel_login.add(jTextField_Login_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 40));

        jPasswordField_Login_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Login_pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Login_pass.setText("password");
        jPasswordField_Login_pass.setOpaque(false);
        jPasswordField_Login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_Login_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_Login_passFocusLost(evt);
            }
        });
        panel_login.add(jPasswordField_Login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 260, 40));

        jButton_Login.setBackground(new java.awt.Color(102, 51, 255));
        jButton_Login.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_Login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Login.setText("Login");
        jButton_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_LoginActionPerformed(evt);
            }
        });
        panel_login.add(jButton_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 40));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_username_32px.png"))); // NOI18N
        panel_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 40));

        forgotPw.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        forgotPw.setForeground(new java.awt.Color(51, 204, 255));
        forgotPw.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        forgotPw.setText("Forgot Password");
        forgotPw.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                forgotPwMouseClicked(evt);
            }
        });
        panel_login.add(forgotPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 250, 30));

        panel_main.add(panel_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 340));

        panel_register.setBackground(new java.awt.Color(255, 255, 255));
        panel_register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(115, 3, 252)));
        panel_register.setPreferredSize(new java.awt.Dimension(300, 290));
        panel_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_phone_32px.png"))); // NOI18N
        panel_register.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        jTextField_Register_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_phone.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_phone.setText("phonenumber");
        jTextField_Register_phone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_phoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_phoneFocusLost(evt);
            }
        });
        jTextField_Register_phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_phoneKeyReleased(evt);
            }
        });
        panel_register.add(jTextField_Register_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, 40));

        jTextField_Register_fullname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_fullname.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_fullname.setText("fullname");
        jTextField_Register_fullname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_fullnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_fullnameFocusLost(evt);
            }
        });
        jTextField_Register_fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_fullnameKeyReleased(evt);
            }
        });
        panel_register.add(jTextField_Register_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 40));

        jTextField_Register_email.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_email.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_email.setText("email");
        jTextField_Register_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_emailFocusLost(evt);
            }
        });
        jTextField_Register_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_emailKeyReleased(evt);
            }
        });
        panel_register.add(jTextField_Register_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        jButton_GeneratePass.setBackground(new java.awt.Color(102, 102, 255));
        jButton_GeneratePass.setFont(new java.awt.Font("SansSerif", 0, 11)); // NOI18N
        jButton_GeneratePass.setForeground(new java.awt.Color(255, 255, 255));
        jButton_GeneratePass.setText("Generate Password");
        jButton_GeneratePass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_GeneratePass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton_GeneratePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GeneratePassActionPerformed(evt);
            }
        });
        panel_register.add(jButton_GeneratePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, 30));

        jCheckBox1.setText("Show Password");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        panel_register.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 120, 30));

        jPasswordField_Register_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_Register_pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_Register_pass.setText("password");
        jPasswordField_Register_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_Register_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_Register_passFocusLost(evt);
            }
        });
        jPasswordField_Register_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_Register_passKeyReleased(evt);
            }
        });
        panel_register.add(jPasswordField_Register_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 260, 40));
        jPasswordField_Register_pass.getAccessibleContext().setAccessibleName("");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_name_32px.png"))); // NOI18N
        panel_register.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 40, 40));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_register.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 40, 40));

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_username_32px.png"))); // NOI18N
        panel_register.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 40));

        jTextField_Register_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_Register_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_Register_username.setText("username");
        jTextField_Register_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_Register_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_Register_usernameFocusLost(evt);
            }
        });
        jTextField_Register_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Register_usernameKeyReleased(evt);
            }
        });
        panel_register.add(jTextField_Register_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 260, 40));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_mail_32px.png"))); // NOI18N
        panel_register.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 40, 40));

        jButton_Register.setBackground(new java.awt.Color(102, 51, 255));
        jButton_Register.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jButton_Register.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Register.setText("Register");
        jButton_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegisterActionPerformed(evt);
            }
        });
        panel_register.add(jButton_Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 290, 40));

        panel_main.add(panel_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 340));

        panel_container.add(panel_main, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 310, 400));

        panel_lupaPass.setBackground(new java.awt.Color(255, 255, 255));
        panel_lupaPass.setPreferredSize(new java.awt.Dimension(310, 400));
        panel_lupaPass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField_pwbaru.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_pwbaru.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_pwbaru.setText("new password");
        jPasswordField_pwbaru.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruFocusLost(evt);
            }
        });
        jPasswordField_pwbaru.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_pwbaruKeyReleased(evt);
            }
        });
        panel_lupaPass.add(jPasswordField_pwbaru, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 260, 40));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_lupaPass.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 40, 40));

        jCheckBox3.setText("Show Password");
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        panel_lupaPass.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 120, 30));

        jPasswordField_pwbaruconfirm.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_pwbaruconfirm.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_pwbaruconfirm.setText("confirm new password");
        jPasswordField_pwbaruconfirm.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruconfirmFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruconfirmFocusLost(evt);
            }
        });
        jPasswordField_pwbaruconfirm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_pwbaruconfirmKeyReleased(evt);
            }
        });
        panel_lupaPass.add(jPasswordField_pwbaruconfirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 260, 40));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_lupaPass.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 40, 40));

        jTextField_emailforgot.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_emailforgot.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_emailforgot.setText("email");
        jTextField_emailforgot.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_emailforgotFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_emailforgotFocusLost(evt);
            }
        });
        jTextField_emailforgot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_emailforgotKeyReleased(evt);
            }
        });
        panel_lupaPass.add(jTextField_emailforgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 260, 40));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_mail_32px.png"))); // NOI18N
        panel_lupaPass.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 40, 40));

        jl_forgot.setBackground(new java.awt.Color(115, 3, 252));
        jl_forgot.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jl_forgot.setForeground(new java.awt.Color(255, 255, 255));
        jl_forgot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_forgot.setText("Forgot Password");
        jl_forgot.setOpaque(true);
        panel_lupaPass.add(jl_forgot, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 40));

        error_pass.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_pass.setForeground(new java.awt.Color(255, 0, 0));
        error_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_lupaPass.add(error_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 30));

        btn_back.setBackground(new java.awt.Color(102, 51, 255));
        btn_back.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        panel_lupaPass.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 260, 40));

        btn_update.setBackground(new java.awt.Color(102, 51, 255));
        btn_update.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        panel_lupaPass.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, 40));

        panel_container.add(panel_lupaPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 310, 400));

        panel_ChangePass.setBackground(new java.awt.Color(255, 255, 255));
        panel_ChangePass.setPreferredSize(new java.awt.Dimension(310, 400));
        panel_ChangePass.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPasswordField_pwlama_cp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_pwlama_cp.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_pwlama_cp.setText("old password");
        jPasswordField_pwlama_cp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pwlama_cpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_pwlama_cpFocusLost(evt);
            }
        });
        jPasswordField_pwlama_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_pwlama_cpKeyReleased(evt);
            }
        });
        panel_ChangePass.add(jPasswordField_pwlama_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 260, 40));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_ChangePass.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 40, 40));

        jPasswordField_pwbaru_cp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_pwbaru_cp.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_pwbaru_cp.setText("new password");
        jPasswordField_pwbaru_cp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaru_cpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaru_cpFocusLost(evt);
            }
        });
        jPasswordField_pwbaru_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_pwbaru_cpKeyReleased(evt);
            }
        });
        panel_ChangePass.add(jPasswordField_pwbaru_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 260, 40));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_ChangePass.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 40, 40));

        jCheckBox4.setText("Show Password");
        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        panel_ChangePass.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 120, 30));

        jPasswordField_pwbaruconfirm_cp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_pwbaruconfirm_cp.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_pwbaruconfirm_cp.setText("confirm new password");
        jPasswordField_pwbaruconfirm_cp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruconfirm_cpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_pwbaruconfirm_cpFocusLost(evt);
            }
        });
        jPasswordField_pwbaruconfirm_cp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField_pwbaruconfirm_cpKeyReleased(evt);
            }
        });
        panel_ChangePass.add(jPasswordField_pwbaruconfirm_cp, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 260, 40));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8_password_32px.png"))); // NOI18N
        panel_ChangePass.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 40, 40));

        jl_cpass.setBackground(new java.awt.Color(115, 3, 252));
        jl_cpass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jl_cpass.setForeground(new java.awt.Color(255, 255, 255));
        jl_cpass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_cpass.setText("Change Password");
        jl_cpass.setOpaque(true);
        panel_ChangePass.add(jl_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 260, 40));

        error_pass1.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        error_pass1.setForeground(new java.awt.Color(255, 0, 0));
        error_pass1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panel_ChangePass.add(error_pass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 260, 30));

        btn_cpass.setBackground(new java.awt.Color(102, 51, 255));
        btn_cpass.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        btn_cpass.setForeground(new java.awt.Color(255, 255, 255));
        btn_cpass.setText("Change Password");
        btn_cpass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cpassActionPerformed(evt);
            }
        });
        panel_ChangePass.add(btn_cpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 260, 40));

        panel_container.add(panel_ChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 310, 400));

        jButton_Reset.setBackground(new java.awt.Color(102, 51, 255));
        jButton_Reset.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton_Reset.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Reset.setText("Reset");
        jButton_Reset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ResetActionPerformed(evt);
            }
        });
        panel_container.add(jButton_Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/close.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        panel_container.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 40, 40, 40));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undraw_Programming_re_kg9v (1) 1.png"))); // NOI18N
        panel_container.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 590, 500));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Rectangle 1.png"))); // NOI18N
        panel_container.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 590, 500));

        getContentPane().add(panel_container, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void jTextField_Login_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Login_usernameFocusGained
        // if the textField = username then clear the username
        String usernameValue = jTextField_Login_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username")) {
            jTextField_Login_username.setText("");
            jTextField_Login_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Login_usernameFocusGained

    private void jTextField_Login_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Login_usernameFocusLost
        // textfield empty -> set text 'username'
        String usernameValue = jTextField_Login_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username") || usernameValue.equals("")) {
            jTextField_Login_username.setText("username");
            jTextField_Login_username.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Login_usernameFocusLost

    private void jPasswordField_Login_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Login_passFocusGained
        // if the jpassword text = password -> clear the textfield
        String passValue = String.valueOf(jPasswordField_Login_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password")) {
            jPasswordField_Login_pass.setText("");
            jPasswordField_Login_pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_Login_passFocusGained

    private void jPasswordField_Login_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Login_passFocusLost
        // password empty -> set pass 'password'
        String passValue = String.valueOf(jPasswordField_Login_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password") || passValue.equals("")) {
            jPasswordField_Login_pass.setText("password");
            jPasswordField_Login_pass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_Login_passFocusLost

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox2.isSelected()) {
            jPasswordField_Login_pass.setEchoChar((char) 0);
        } else {
            jPasswordField_Login_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jButton_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_LoginActionPerformed
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM user WHERE username = '"
                    + jTextField_Login_username.getText()
                    + "' AND password = '" + jPasswordField_Login_pass.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rsLogin = st.executeQuery(query);
            rsLogin.next();
            if (rsLogin.getRow() == 1) {
                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                clear();
                user = new User(rsLogin.getString("fullname"),
                        rsLogin.getString("username"),
                        rsLogin.getString("email"),
                        rsLogin.getString("phonenumber"),
                        rsLogin.getString("password"));
                new MainMenu().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Login gagal!");
                clear();
            }
        } catch (HeadlessException | SQLException e) {

        }
    }//GEN-LAST:event_jButton_LoginActionPerformed

    private void jl_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_LoginMouseClicked
        panel_login.setVisible(true);
        panel_register.setVisible(false);
        // design jLabel Login click
        jl_Login.setBorder(red_top_border);
        jl_Login.setBackground(Color.white);
        jl_Login.setForeground(Color.black);

        // design jLabel register click
        jl_Register.setBorder(default_top_border);
        jl_Register.setBackground(new Color(115, 3, 252));
        jl_Register.setForeground(Color.white);
    }//GEN-LAST:event_jl_LoginMouseClicked

    private void jl_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_RegisterMouseClicked
        panel_register.setVisible(true);
        panel_login.setVisible(false);
        // design jLabel register click
        jl_Register.setBorder(red_top_border);
        jl_Register.setBackground(Color.white);
        jl_Register.setForeground(Color.black);

        // design jLabel login click
        jl_Login.setBorder(default_top_border);
        jl_Login.setBackground(new Color(115, 3, 252));
        jl_Login.setForeground(Color.white);
    }//GEN-LAST:event_jl_RegisterMouseClicked

    private void jTextField_Register_fullnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_fullnameFocusGained
        // TODO add your handling code here:
        String fullnameValue = jTextField_Register_fullname.getText().trim().toLowerCase();

        if (fullnameValue.equals("fullname")) {
            jTextField_Register_fullname.setText("");
            jTextField_Register_fullname.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_fullnameFocusGained

    private void jTextField_Register_fullnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_fullnameFocusLost
        // TODO add your handling code here:
        // textfield empty -> set text 'fullname'
        String fullnameValue = jTextField_Register_fullname.getText().trim().toLowerCase();

        if (fullnameValue.equals("fullname") || fullnameValue.equals("")) {
            jTextField_Register_fullname.setText("fullname");
            jTextField_Register_fullname.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_fullnameFocusLost

    private void jTextField_Register_fullnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_fullnameKeyReleased
        // TODO add your handling code here:
        if (jTextField_Register_fullname.getText().matches("[a-zA-Z ]+")) {
            flag1 = true;
        } else {
            flag1 = false;
        }
    }//GEN-LAST:event_jTextField_Register_fullnameKeyReleased

    private void jTextField_Register_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_emailFocusGained
        // TODO add your handling code here:
        String email = jTextField_Register_email.getText().trim().toLowerCase();

        if (email.equals("email")) {
            jTextField_Register_email.setText("");
            jTextField_Register_email.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_emailFocusGained

    private void jTextField_Register_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_emailFocusLost
        // TODO add your handling code here:
        String email = jTextField_Register_email.getText().trim().toLowerCase();

        if (email.equals("email") || email.equals("")) {
            jTextField_Register_email.setText("email");
            jTextField_Register_email.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_emailFocusLost

    private void jTextField_Register_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_emailKeyReleased
        if (jTextField_Register_email.getText().matches("[a-zA-Z0-9._]+@([a-zA-Z]{2,5})+(\\.[a-z]{2,5})+")) {
            flag3 = true;
            db.koneksiDatabase();
            try {
                String query = "SELECT * FROM user WHERE email = '" + jTextField_Register_email.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rsLogin = st.executeQuery(query);
                rsLogin.next();
                if (rsLogin.getRow() == 1) {
                    JOptionPane.showMessageDialog(null, "Email sudah terdaftar di database!\nSilakan memakai Email lain!");
                    jTextField_Register_email.setText("");
                    flag3 = false;
                } else {
                    flag3 = true;
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            flag3 = false;
        }
    }//GEN-LAST:event_jTextField_Register_emailKeyReleased

    private void jPasswordField_Register_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_Register_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password")) {
            jPasswordField_Register_pass.setText("");
            jPasswordField_Register_pass.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_Register_passFocusGained

    private void jPasswordField_Register_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_Register_pass.getPassword()).trim().toLowerCase();

        if (passValue.equals("password") || passValue.equals("")) {
            jPasswordField_Register_pass.setText("password");
            jPasswordField_Register_pass.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_Register_passFocusLost

    private void jPasswordField_Register_passKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_Register_passKeyReleased
        if (jPasswordField_Register_pass.getText().matches("[A-Za-z0-9]+")) {
            flag5 = true;
        } else {
            flag5 = false;
        }
    }//GEN-LAST:event_jPasswordField_Register_passKeyReleased

    private void jButton_GeneratePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GeneratePassActionPerformed
        // TODO add your handling code here:
        jPasswordField_Register_pass.setText(generateRegex());
        jPasswordField_Register_pass.setForeground(Color.black);
    }//GEN-LAST:event_jButton_GeneratePassActionPerformed
// generate Regex PASSWORD

    private String generateRegex() {
        String pattern = "[^A-Za-z0-9]+";
        // 256 Character
        byte[] array = new byte[256];
        new Random().nextBytes(array);
        String randomString = new String(array, Charset.forName("UTF-8"));
        // StringBuilder untuk mengisi regex.charAt di dalam for
        StringBuilder result = new StringBuilder();
        // assignment pattern
        String regex = randomString.replaceAll(pattern, "");
        // generate password dengan panjang random 8-12 dengan ketentuan pattern regex
        int n = 12;
        for (int i = 0; i <= new Random().nextInt(8) + 5; i++) {
            if (Character.isLetter(regex.charAt(i)) && (n > 0) || Character.isDigit(regex.charAt(i)) && (n > 0)) {
                result.append(regex.charAt(i));
                n--;
            }
        }
        flag5 = true;
        // mengembalikan result
        return result.toString();

    }
    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox1.isSelected()) {
            jPasswordField_Register_pass.setEchoChar((char) 0);
        } else {
            jPasswordField_Register_pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jTextField_Register_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameFocusGained
        // TODO add your handling code here:
        String usernameValue = jTextField_Register_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username")) {
            jTextField_Register_username.setText("");
            jTextField_Register_username.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_usernameFocusGained

    private void jTextField_Register_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameFocusLost
        String usernameValue = jTextField_Register_username.getText().trim().toLowerCase();

        if (usernameValue.equals("username") || usernameValue.equals("")) {
            jTextField_Register_username.setText("username");
            jTextField_Register_username.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_usernameFocusLost

    private void jTextField_Register_usernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_usernameKeyReleased
        // TODO add your handling code here:
        if (jTextField_Register_username.getText().matches("[a-zA-Z0-9.-_]+")) {
            flag2 = true;
            db.koneksiDatabase();
            try {
                String query = "SELECT * FROM user WHERE username = '" + jTextField_Register_username.getText() + "'";
                Statement st = db.getKoneksi().createStatement();
                ResultSet rsLogin = st.executeQuery(query);
                rsLogin.next();
                if (rsLogin.getRow() == 1) {
                    JOptionPane.showMessageDialog(null, "Username sudah terdaftar di database!\nSilakan memakai Username lain!");
                    jTextField_Register_username.setText("");
                    flag2 = false;
                } else {
                    flag2 = true;
                }
            } catch (HeadlessException | SQLException e) {
                e.printStackTrace();
            }
        } else {
            flag2 = false;
        }
    }//GEN-LAST:event_jTextField_Register_usernameKeyReleased

    private void jButton_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegisterActionPerformed
        // TODO add your handling code here:
        if (flag1 && flag2 && flag3 && flag4 && flag5) {
            db.koneksiDatabase();
            try {
                Connection dbconnect = db.getKoneksi();
                String query = " insert into user (fullname, username, email, phonenumber, password, total_transaction)"
                        + " values(?, ?, ?, ?, ?, ?)";
                PreparedStatement myStatement = dbconnect.prepareStatement(query);
                myStatement.setString(1, jTextField_Register_fullname.getText());
                myStatement.setString(2, jTextField_Register_username.getText());
                myStatement.setString(3, jTextField_Register_email.getText());
                myStatement.setString(4, jTextField_Register_phone.getText());
                myStatement.setString(5, jPasswordField_Register_pass.getText());
                myStatement.setInt(6, 0);
                myStatement.execute();
                try {
                    String query1 = "SELECT * FROM user WHERE username = '" + jTextField_Register_username.getText() + "'";
                    Statement st = db.getKoneksi().createStatement();
                    ResultSet rsLogin = st.executeQuery(query1);
                    rsLogin.next();
                    String query2 = " insert into membership (id, status, points)"
                            + " values(?, ?, ?)";
                    PreparedStatement myStatement1 = dbconnect.prepareStatement(query2);
                    myStatement1.setInt(1, rsLogin.getInt("ID"));
                    myStatement1.setString(2, "");
                    myStatement1.setInt(3, 0);
                    myStatement1.execute();
                } catch (Exception e) {
                    e.printStackTrace();
                }

                JOptionPane.showMessageDialog(null, "Registrasi Berhasil!");
                clear();
            } catch (Exception e) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "ERROR REGISTRASI TIDAK VALID!", "WARNING", JOptionPane.ERROR_MESSAGE);
            clear();
        }
    }//GEN-LAST:event_jButton_RegisterActionPerformed

    private void jButton_ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ResetActionPerformed
        clear();
    }//GEN-LAST:event_jButton_ResetActionPerformed

    private void jTextField_Register_phoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_phoneFocusGained
        String phoneValue = jTextField_Register_phone.getText().trim().toLowerCase();

        if (phoneValue.equals("phonenumber")) {
            jTextField_Register_phone.setText("");
            jTextField_Register_phone.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_Register_phoneFocusGained

    private void jTextField_Register_phoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_Register_phoneFocusLost
        String phoneValue = jTextField_Register_phone.getText().trim().toLowerCase();

        if (phoneValue.equals("phonenumber") || phoneValue.equals("")) {
            jTextField_Register_phone.setText("phonenumber");
            jTextField_Register_phone.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_Register_phoneFocusLost

    private void jTextField_Register_phoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Register_phoneKeyReleased
        // TODO add your handling code here:
        if (jTextField_Register_phone.getText().matches("[0-9]{12,13}+")) {
            flag4 = true;
        } else {
            flag4 = false;
        }
    }//GEN-LAST:event_jTextField_Register_phoneKeyReleased

    private void jPasswordField_pwbaruFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaru.getPassword()).trim().toLowerCase();

        if (passValue.equals("new password")) {
            jPasswordField_pwbaru.setText("");
            jPasswordField_pwbaru.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_pwbaruFocusGained

    private void jPasswordField_pwbaruFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaru.getPassword()).trim().toLowerCase();

        if (passValue.equals("new password") || passValue.equals("")) {
            jPasswordField_pwbaru.setText("new password");
            jPasswordField_pwbaru.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_pwbaruFocusLost

    private void jPasswordField_pwbaruKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pwbaruKeyReleased

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if (jCheckBox3.isSelected()) {
            jPasswordField_pwbaru.setEchoChar((char) 0);
            jPasswordField_pwbaruconfirm.setEchoChar((char) 0);
        } else {
            jPasswordField_pwbaru.setEchoChar('*');
            jPasswordField_pwbaruconfirm.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jPasswordField_pwbaruconfirmFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirmFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaruconfirm.getPassword()).trim().toLowerCase();

        if (passValue.equals("confirm new password")) {
            jPasswordField_pwbaruconfirm.setText("");
            jPasswordField_pwbaruconfirm.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_pwbaruconfirmFocusGained

    private void jPasswordField_pwbaruconfirmFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirmFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaruconfirm.getPassword()).trim().toLowerCase();

        if (passValue.equals("confirm new password") || passValue.equals("")) {
            jPasswordField_pwbaruconfirm.setText("confirm new password");
            jPasswordField_pwbaruconfirm.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_pwbaruconfirmFocusLost

    private void jPasswordField_pwbaruconfirmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirmKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pwbaruconfirmKeyReleased

    private void jTextField_emailforgotFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailforgotFocusGained
        // TODO add your handling code here:
        String email = jTextField_emailforgot.getText().trim().toLowerCase();

        if (email.equals("email")) {
            jTextField_emailforgot.setText("");
            jTextField_emailforgot.setForeground(Color.black);
        }
    }//GEN-LAST:event_jTextField_emailforgotFocusGained

    private void jTextField_emailforgotFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_emailforgotFocusLost
        // TODO add your handling code here:
        String email = jTextField_emailforgot.getText().trim().toLowerCase();

        if (email.equals("email") || email.equals("")) {
            jTextField_emailforgot.setText("email");
            jTextField_emailforgot.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jTextField_emailforgotFocusLost

    private void jTextField_emailforgotKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_emailforgotKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_emailforgotKeyReleased

    private void forgotPwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_forgotPwMouseClicked
        // TODO add your handling code here:
        panel_main.setVisible(false);
        panel_lupaPass.setVisible(true);
        jl_forgot.setBorder(red_top_border);
        jl_forgot.setBackground(Color.white);
        jl_forgot.setForeground(Color.black);
    }//GEN-LAST:event_forgotPwMouseClicked

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        panel_lupaPass.setVisible(false);
        panel_main.setVisible(true);
        panel_login.setVisible(true);
        panel_register.setVisible(false);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        db.koneksiDatabase();
        try {
            String query = "SELECT * FROM user WHERE email = '" + jTextField_emailforgot.getText() + "'";
            Statement st = db.getKoneksi().createStatement();
            ResultSet rsLogin = st.executeQuery(query);
            rsLogin.next();
            if (jTextField_emailforgot.getText().matches("[a-zA-Z0-9._]+@([a-zA-Z]{2,5})+(\\.[a-z]{2,5})+")) {
                if (rsLogin.getRow() == 1) {
                    if (jPasswordField_pwbaru.getText().matches("[0-9a-zA-Z]+")) {
                        if (jPasswordField_pwbaru.getText().equals(jPasswordField_pwbaruconfirm.getText())) {
                            String queryup = "update user set password = ? where email = ?";
                            PreparedStatement state = db.getKoneksi().prepareStatement(queryup);
                            state.setString(1, jPasswordField_pwbaru.getText());
                            state.setString(2, jTextField_emailforgot.getText());
                            state.execute();
                            JOptionPane.showMessageDialog(null, "Password berhasil diperbarui!");
                            clear();
                            panel_main.setVisible(true);
                            panel_lupaPass.setVisible(false);
                        } else {
                            JOptionPane.showMessageDialog(null, "Password tidak sinkron!");
                            clear();
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Email tidak tersedia!");
                    clear();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email tidak valid!");
                clear();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void jPasswordField_pwbaru_cpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaru_cpFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaru_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("new password")) {
            jPasswordField_pwbaru_cp.setText("");
            jPasswordField_pwbaru_cp.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_pwbaru_cpFocusGained

    private void jPasswordField_pwbaru_cpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaru_cpFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaru_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("new password") || passValue.equals("")) {
            jPasswordField_pwbaru_cp.setText("new password");
            jPasswordField_pwbaru_cp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_pwbaru_cpFocusLost

    private void jPasswordField_pwbaru_cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaru_cpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pwbaru_cpKeyReleased

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
        if (jCheckBox4.isSelected()) {
            jPasswordField_pwlama_cp.setEchoChar((char) 0);
            jPasswordField_pwbaru_cp.setEchoChar((char) 0);
            jPasswordField_pwbaruconfirm_cp.setEchoChar((char) 0);
        } else {
            jPasswordField_pwlama_cp.setEchoChar('*');
            jPasswordField_pwbaru_cp.setEchoChar('*');
            jPasswordField_pwbaruconfirm_cp.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jPasswordField_pwbaruconfirm_cpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirm_cpFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaruconfirm_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("confirm new password")) {
            jPasswordField_pwbaruconfirm_cp.setText("");
            jPasswordField_pwbaruconfirm_cp.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_pwbaruconfirm_cpFocusGained

    private void jPasswordField_pwbaruconfirm_cpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirm_cpFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwbaruconfirm_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("confirm new password") || passValue.equals("")) {
            jPasswordField_pwbaruconfirm_cp.setText("confirm new password");
            jPasswordField_pwbaruconfirm_cp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_pwbaruconfirm_cpFocusLost

    private void jPasswordField_pwbaruconfirm_cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pwbaruconfirm_cpKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_jPasswordField_pwbaruconfirm_cpKeyReleased

    private void btn_cpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cpassActionPerformed
        // TODO add your handling code here:
        db.koneksiDatabase();
        try {
            Statement statement = db.getKoneksi().createStatement();
            ResultSet rs = statement.executeQuery("SELECT * FROM user WHERE username = '" + this.getUsername() + "'");
            rs.next();
            if (rs.getRow() == 1) {
                if (jPasswordField_pwlama_cp.getText().equals(rs.getString("password"))) {
                    if (jPasswordField_pwbaru_cp.getText().matches("[0-9a-zA-Z]+")
                            && jPasswordField_pwbaru_cp.getText().equals(jPasswordField_pwbaruconfirm_cp.getText())) {
                        try {
                            String query = "update user set password = ? where username = ? ";
                            PreparedStatement state = db.getKoneksi().prepareStatement(query);
                            state.setString(1, jPasswordField_pwbaru_cp.getText());
                            state.setString(2, getUsername());
                            state.execute();
                            JOptionPane.showMessageDialog(null, "Update Password Berhasil!");
                            new LoginAndRegisterForm().setVisible(true);
                            this.dispose();
                            clear();
                        } catch (Exception e) {

                        }
                    } else {
                        JOptionPane.showMessageDialog(null, "Password baru tidak sinkron atau memakai symbol!");
                        clear();
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Password lama tidak sesuai!");
                    clear();
                }
            }
        } catch (Exception e) {

        }

    }//GEN-LAST:event_btn_cpassActionPerformed

    private void jPasswordField_pwlama_cpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwlama_cpFocusGained
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwlama_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("old password")) {
            jPasswordField_pwlama_cp.setText("");
            jPasswordField_pwlama_cp.setForeground(Color.black);
        }
    }//GEN-LAST:event_jPasswordField_pwlama_cpFocusGained

    private void jPasswordField_pwlama_cpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_pwlama_cpFocusLost
        // TODO add your handling code here:
        String passValue = String.valueOf(jPasswordField_pwlama_cp.getPassword()).trim().toLowerCase();

        if (passValue.equals("old password") || passValue.equals("")) {
            jPasswordField_pwlama_cp.setText("old password");
            jPasswordField_pwlama_cp.setForeground(new Color(153, 153, 153));
        }
    }//GEN-LAST:event_jPasswordField_pwlama_cpFocusLost

    private void jPasswordField_pwlama_cpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_pwlama_cpKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_pwlama_cpKeyReleased

    public void clear() {
        jTextField_Login_username.setText("username");
        jPasswordField_Login_pass.setText("password");
        jTextField_Register_fullname.setText("fullname");
        jTextField_Register_username.setText("username");
        jTextField_Register_email.setText("email");
        jPasswordField_Register_pass.setText("password");
        jTextField_Register_phone.setText("phonenumber");
        jTextField_emailforgot.setText("email");
        jPasswordField_pwbaru.setText("new password");
        jPasswordField_pwbaruconfirm.setText("confirm new password");
        jPasswordField_pwlama_cp.setText("old password");
        jPasswordField_pwbaru_cp.setText("new password");
        jPasswordField_pwbaruconfirm_cp.setText("confirm new password");

        jTextField_Register_username.setForeground(new Color(153, 153, 153));
        jPasswordField_Register_pass.setForeground(new Color(153, 153, 153));
        jTextField_Register_email.setForeground(new Color(153, 153, 153));
        jTextField_Register_fullname.setForeground(new Color(153, 153, 153));
        jPasswordField_Login_pass.setForeground(new Color(153, 153, 153));
        jTextField_Login_username.setForeground(new Color(153, 153, 153));
        jTextField_Register_phone.setForeground(new Color(153, 153, 153));
        jTextField_emailforgot.setForeground(new Color(153, 153, 153));
        jPasswordField_pwbaru.setForeground(new Color(153, 153, 153));
        jPasswordField_pwbaruconfirm.setForeground(new Color(153, 153, 153));
        jPasswordField_pwlama_cp.setForeground(new Color(153, 153, 153));
        jPasswordField_pwbaru_cp.setForeground(new Color(153, 153, 153));
        jPasswordField_pwbaruconfirm_cp.setForeground(new Color(153, 153, 153));

        jPasswordField_Register_pass.setEchoChar('*');
        jPasswordField_Login_pass.setEchoChar('*');
        jPasswordField_pwbaru.setEchoChar('*');
        jPasswordField_pwbaruconfirm.setEchoChar('*');
        jPasswordField_pwlama_cp.setEchoChar('*');
        jPasswordField_pwbaru_cp.setEchoChar('*');
        jPasswordField_pwbaruconfirm_cp.setEchoChar('*');

        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAndRegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LoginAndRegisterForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cpass;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel error_pass;
    private javax.swing.JLabel error_pass1;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel forgotPw;
    private javax.swing.JButton jButton_GeneratePass;
    private javax.swing.JButton jButton_Login;
    private javax.swing.JButton jButton_Register;
    private javax.swing.JButton jButton_Reset;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField_Login_pass;
    private javax.swing.JPasswordField jPasswordField_Register_pass;
    private javax.swing.JPasswordField jPasswordField_pwbaru;
    private javax.swing.JPasswordField jPasswordField_pwbaru_cp;
    private javax.swing.JPasswordField jPasswordField_pwbaruconfirm;
    private javax.swing.JPasswordField jPasswordField_pwbaruconfirm_cp;
    private javax.swing.JPasswordField jPasswordField_pwlama_cp;
    private javax.swing.JTextField jTextField_Login_username;
    private javax.swing.JTextField jTextField_Register_email;
    private javax.swing.JTextField jTextField_Register_fullname;
    private javax.swing.JTextField jTextField_Register_phone;
    private javax.swing.JTextField jTextField_Register_username;
    private javax.swing.JTextField jTextField_emailforgot;
    private javax.swing.JLabel jl_Login;
    private javax.swing.JLabel jl_Register;
    private javax.swing.JLabel jl_cpass;
    private javax.swing.JLabel jl_forgot;
    private javax.swing.JPanel panel_ChangePass;
    private javax.swing.JPanel panel_container;
    private javax.swing.JPanel panel_login;
    private javax.swing.JPanel panel_lupaPass;
    private javax.swing.JPanel panel_main;
    private javax.swing.JPanel panel_register;
    // End of variables declaration//GEN-END:variables
    private String username;

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}
